### ISSUE TITLE
在最新folia1.20.4中使用时他会出现错误

### ISSUE THREAD

**Issue by buildin1** [sjavi4/Spigot_ShulkerBoxNBTCrafter#1]
[01:46:33 ERROR]: Could not pass event PrepareItemCraftEvent to SBCrafter v1.2
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at me.autobot.sbcrafter.utility.RecipeHandler.registerRecipe(RecipeHandler.java:118) ~[[盒子内合成物品]SBCrafter-1.2.jar:?]
        at me.autobot.sbcrafter.listener.OnCraft.onPrepareCraft(OnCraft.java:77) ~[[盒 子内合成物品]SBCrafter-1.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor280.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:git-Luminol-"54da545"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1444) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.world.inventory.CraftingMenu.slotChangedCraftingGrid(CraftingMenu.java:94) ~[?:?]
        at net.minecraft.world.inventory.CraftingMenu.lambda$slotsChanged$0(CraftingMenu.java:105) ~[?:?]
        at net.minecraft.world.inventory.ContainerLevelAccess.lambda$execute$0(ContainerLevelAccess.java:85) ~[?:?]
        at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:72) ~[?:?]
        at net.minecraft.world.inventory.ContainerLevelAccess.execute(ContainerLevelAccess.java:84) ~[?:?]
        at net.minecraft.world.inventory.CraftingMenu.slotsChanged(CraftingMenu.java:104) ~[?:?]
        at net.minecraft.world.inventory.TransientCraftingContainer.setItem(TransientCraftingContainer.java:147) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.world.inventory.Slot.set(Slot.java:67) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.world.inventory.Slot.setByPlayer(Slot.java:63) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.world.inventory.Slot.setByPlayer(Slot.java:59) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.world.inventory.Slot.safeInsert(Slot.java:137) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:556) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3211) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:102) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1638) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"54da545"]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by sjavi4** [comment]
Problem Fixed by changing the check for Folia server.
Please check v1.4 for the fixed version
